package bsim;

import bsim.transport.BSimConservativeTransport;
import bsim.transport.BSimTransportBoundary;
import bsim.transport.BSimTransportLedger;

import javax.vecmath.Vector3d;

/**
 * Standard chemical field (uniform division of space) .
 * Uses regular division of the three-dimensional space into boxes that
 * then allow for diffusion of chemical quantities between the boxes at
 * some rate (diffusivity).
 */
public class BSimChemicalField {
	
	/* 1 molecule/(micron)^3 = 1.7 nM = 1.7 nanomol/L */
	/* 1 mM = 6e5 molecules/(micron)^3 */
	
	/** Simulation the chemical field is associated with. */
	protected BSim sim;
	/** Diffusivity of the chemical field. */
	protected double diffusivity; // (microns)^2/s
	/** First-order decay constant; quantity(t+dt) = quantity(t)*exp(-decayRate*dt). */
	protected double decayRate; // 1/seconds 
	/** The quantity of chemical in the box (i,j,k). */
	protected double[][][] quantity; // number of molecules
	/** sim.getBound(). */
	protected Vector3d bound;
	/** Number of boxes in each dimension. */
	protected int[] boxes = new int[3];
	/** Box size. */
	protected double[] box = new double[3]; // microns
	/** Volume of each box (microns^3). */
	protected double boxVolume;
	/** All-fluid geometry used by the standard unmasked field. */
	protected boolean[][][] allFluidMask;
	/** Cumulative losses generated by transport and decay calls. */
	protected final BSimTransportLedger transportLedger = new BSimTransportLedger();
	protected double lastBoundaryLoss;
	protected double lastDecayLoss;
	
	/**
	 * Constructor that creates a new chemical field with attached to a particular simulation and
	 * with a specified number of boxes, chemical diffusivity and decay rate.
	 * @param sim Associated simulation.
	 * @param boxes Number of boxes in the (x,y,z) directions.
	 * @param diffusivity Diffusivity of the chemical (microns)^2/s.
	 * @param decayRate First-order decay constant (1/s).
	 */
	public BSimChemicalField(BSim sim, int[] boxes, double diffusivity, double decayRate) {
		this.sim = sim;
		this.bound = sim.getBound();
		this.boxes = boxes;
		box[0] = bound.x/(double)boxes[0];
		box[1] = bound.y/(double)boxes[1];
		box[2] = bound.z/(double)boxes[2];
		boxVolume = box[0]*box[1]*box[2];
		this.quantity = new double[boxes[0]][boxes[1]][boxes[2]]; 
		this.allFluidMask = BSimConservativeTransport.allFluid(boxes);
		this.diffusivity = diffusivity;
		this.decayRate = decayRate;
	}	
	
	/** Return the number of boxes in (x,y,z) directions. */
	public int[] getBoxes() { return boxes; }
	/** Return the size of each box (x,y,z) in microns. */
	public double[] getBox() { return box; }	
	
	/**
	 * Creates a linear concentration gradient in the direction specified by 'axis' (x=0, y=1, z=2)
	 */
	public void linearGradient(int axis, double startConc, double endConc) {
		assert ((axis >= 0) && (axis <= 2)) :
			"Chemical field gradient - axis selection out of range [0,2]\n" +
			"Check axis is one of: x-axis = '0', y = '1', or z = '2'";
		
		
		int[] index = {0,0,0};
		
		double grad = (endConc - startConc)/(double)boxes[axis];
        
        for(index[0] = 0; index[0]<boxes[0]; index[0]++)
			for(index[1] = 0; index[1]<boxes[1]; index[1]++)
				for(index[2] = 0; index[2]<boxes[2]; index[2]++)
					setConc(index[0], index[1], index[2], startConc + index[axis]*grad);
	}
	
	/** Adds a quantity of chemical to the box containing position v. */
	public void addQuantity(Vector3d v, double q) {
		int[] b = boxCoords(v);
		addQuantity(b[0],b[1],b[2],q);
	}
	/** Adds a quantity of chemical to the box (x,y,z). */
	public void addQuantity(int x, int y, int z, double q) {
		quantity[x][y][z] += q;
		if(quantity[x][y][z] < 0) quantity[x][y][z] = 0;
	}
	/** Adds and accounts for a nonnegative external source in molecules. */
	public void addSourceQuantity(Vector3d v, double q) {
		int[] b = boxCoords(v);
		addSourceQuantity(b[0], b[1], b[2], q);
	}
	/** Adds and accounts for a nonnegative external source in molecules. */
	public void addSourceQuantity(int x, int y, int z, double q) {
		if (!Double.isFinite(q) || q < 0.0)
			throw new IllegalArgumentException(
					"source quantity must be finite and nonnegative: " + q);
		quantity[x][y][z] += q;
		transportLedger.addSource(q);
	}
	
	/** Sets the concentration of the box containing position v. */
	public void setConc(Vector3d v, double c) {
		int[] b = boxCoords(v);
		setConc(b[0],b[1],b[2],c);
	}
	/** Sets the concentration of the box (x,y,z). */
	public void setConc(int x, int y, int z, double c) {
		quantity[x][y][z] = c*boxVolume;
	}
	/** Sets the concentration of the field */
	public void setConc(double c) {		
		for(int i=0;i<boxes[0];i++)
			for(int j=0;j<boxes[1];j++)
				for(int k=0;k<boxes[2];k++) quantity[i][j][k] = c*boxVolume;
	}
	
	/** Gets the concentration of the field at the position v in molecules/(micron)^3. */
	public double getConc(Vector3d v) {
		int[] b = boxCoords(v);
		return getConc(b[0],b[1],b[2]);
	}	
	/** Gets the concentration of the field in the box (x,y,z) in molecules/(micron)^3. */
	public double getConc(int i, int j, int k) {
		return quantity[i][j][k]/boxVolume;
	}
	
	/** Returns the total quantity of chemical in the field. */
	public double totalQuantity() {
		double t = 0;
		for(int i=0;i<boxes[0];i++)
			for(int j=0;j<boxes[1];j++)
				for(int k=0;k<boxes[2];k++) t += quantity[i][j][k];
		return t;
	}

	/** Boundary loss generated by the most recent diffusion call. */
	public double getLastBoundaryLoss() { return lastBoundaryLoss; }
	/** Decay loss generated by the most recent decay call. */
	public double getLastDecayLoss() { return lastDecayLoss; }
	/** Cumulative transport/decay accounting for this field. */
	public BSimTransportLedger getTransportLedger() { return transportLedger; }
	
	/** Returns the integer coordinates of the box containing the position v. */ 
	public int[] boxCoords(Vector3d v) {
		/* Check the bounds are valid */
		int x = (int)(v.x/box[0]);
		int y = (int)(v.y/box[1]);
		int z = (int)(v.z/box[2]);
		x = (x >= boxes[0] ? boxes[0]-1 : x);
		y = (y >= boxes[1] ? boxes[1]-1 : y);
		z = (z >= boxes[2] ? boxes[2]-1 : z);
		if (x < 0) x = 0;
		if (y < 0) y = 0;
		if (z < 0) z = 0;
		return new int[] {x, y, z};	
	}
	
	/**
	 * Update the chemical field by diffusing and decaying the chemical present.
	 */
	public void update() {
		diffuse();
		decay();
	}
	
	/**
	 * Decay the chemical present in the field.
	 */
	public void decay() {
		decay(sim.getDt());
	}

	/**
	 * Apply exact first-order decay for an explicit duration.
	 */
	public void decay(double duration) {
		if (!Double.isFinite(duration) || duration < 0.0)
			throw new IllegalArgumentException("decay duration must be finite and nonnegative");
		if (!Double.isFinite(decayRate) || decayRate < 0.0)
			throw new IllegalArgumentException("decay rate must be finite and nonnegative");
		double before = totalQuantity();
		double keep = Math.exp(-decayRate*duration);
		for(int i=0;i<boxes[0];i++)
			for(int j=0;j<boxes[1];j++)
				for(int k=0;k<boxes[2];k++) quantity[i][j][k] *= keep;
		lastDecayLoss = before - totalQuantity();
		transportLedger.addDecayLoss(lastDecayLoss);
	}
	
	/**
	 * Diffuse the chemical present in the field.
	 */
	public void diffuse() {
		diffuse(sim.getDt());
	}

	/**
	 * Diffuse for an explicit duration. Excessive explicit steps are split into
	 * stable FTCS substeps; nominal diffusivity is never rescaled.
	 */
	public void diffuse(double duration) {
		double beforeLoss = transportLedger.getBoundaryLoss();
		quantity = BSimConservativeTransport.diffuse(
				quantity, allFluidMask, box, diffusivity, duration,
				BSimTransportBoundary.fromSimulation(sim), transportLedger);
		lastBoundaryLoss = transportLedger.getBoundaryLoss() - beforeLoss;
	}
	
}
