config.include=sim_config_stage3b.properties
input.ahl.file=input_ahl_balanced40_perm3.txt
rng.seed=33
output.run.label=stage3b_fast_receiver_128000000
output.stochastic.replicate=perm3_rep3
output.dir=results/stage3b_perm3_rep3
